# 谓词匹配配置
spring:
  cloud:
    gateway:
      routes:
        - id: after_route
          uri: http://httpbin.org
          predicates:
            - After=2017-01-20T17:42:47.789-07:00[America/Denver]
#---
# 当请求的Header中有X-Request-Id的header名，且header值为数字时，请求会被路由到配置的 uri.
#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: header_route
#          uri: http://httpbin.org
#          predicates:
#            - Header=X-Request-Id, \d+
#---
## 请求带有cookie名为 name, cookie值为demo 的请求将都会转发到uri
#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: cookie_route
#          uri: http://httpbin.org
#          predicates:
#            - Cookie=name, demo
#---
## 请求头中含有Host为test.com的请求将会被路由转发转发到配置的uri
#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: host_route
#          uri: http://httpbin.org
#          predicates:
#            - Host=**.test.com
#  profiles: host_route
#
#---
## 所有的GET类型的请求都会路由转发到配置的uri
#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: method_route
#          uri: http://httpbin.org
#          predicates:
#            - Method=GET
#  profiles: method_route
#
#---
## 所有的请求路径满足/foo/{segment}的请求将会匹配并被路由，比如/foo/1 、/foo/bar的请求，将会命中匹配，并成功转发
#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: path_route
#          uri: http://httpbin.org
#          predicates:
#            - Path=/foo/{segment}

