server:
  port: 9601
spring:
  application:
    name: apollo-client

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka

apollo:
  bootstrap:
    enabled: true
    namespaces: application
  meta: http://localhost:8080