server:
  port: 9002
spring:
  application:
  name: eureka-server

# \u5411peer2\u6CE8\u518C\u81EA\u8EAB \u4E0Epeer3\u5F62\u6210"peer"
eureka:
  instance:
    hostname: peer1
    prefer-ip-address: true
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://127.0.0.1:9003/eureka

  server:
    waitTimeInMsWhenSyncEmpty: 0
    # \u81EA\u6211\u6559\u7814\uFF0C\u9ED8\u8BA4\u5F00\u542F\uFF0C\u4E3A\u4E86\u6D4B\u8BD5\u5173\u95ED
    enableSelfPreservation: false