server:
  port: 9004
spring:
  application:
  name: eureka-server

eureka:
  instance:
    hostname: peer3
    prefer-ip-address: true
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
#      向peer1,peer2注册
      defaultZone: http://127.0.0.1:9002/eureka,http://127.0.0.1:9002/eureka

  server:
    waitTimeInMsWhenSyncEmpty: 0
    enableSelfPreservation: false