server:
  port: 9003
spring:
  application:
  name: eureka-server

eureka:
  instance:
    hostname: peer2
    prefer-ip-address: true
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://127.0.0.1:9002/eureka

  server:
    waitTimeInMsWhenSyncEmpty: 0
    enableSelfPreservation: false